[package]
name = "sharedcockpit"
version = "2.3.0"
license = "Apache 2.0"
repository = "https://github.com/Sequal32/yourcontrols"
authors = ["Connor T <connor0530@gmail.com>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
attohttpc = {version = "0.16", features = ["json"]}
base64 = "0.13"
bimap = {version = "0.5", features = ["serde"]}
byteorder = "1.3"
chrono = "0.4"
crossbeam-channel = "0.4"
dns-lookup = "1.0"
igd = "0.11"
indexmap = {version = "1.6", features = ["serde-1"]}
local_ipaddress = "0.1"
log = "0.4"
num = "0.3"
semver = "0.11"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
serde_yaml = "0.8"
simconnect = "0.1.3"
simplelog = "0.8"
spin_sleep = "1.0"
util = "0.1.2"
web-view = "0.6"
zip = "0.5"

[dev-dependencies]
web-view = { version = "0.6", features = ["edge"]}

[build-dependencies]
winres = "0.1"